-- Legacy optional-service bootstrap intentionally left empty.
-- Phase 0 AI Compute Control Plane owns only the gpu_platform database declared
-- by POSTGRES_DB. Schema creation is exclusively managed by Alembic.
--
-- Optional services such as MLflow must provision their own database/schema in
-- their Compose profile or deployment chart; they are not part of P0 startup.
